//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSSecureTextField, NSTextField;

@interface JGAuthRequest : NSWindowController
{
    NSButton *cancelButton;
    NSButton *loginButton;
    NSTextField *msgTextField;
    NSSecureTextField *passwordTextField;
    NSTextField *usernameTextField;
    NSButton *savePasswordButton;
}

- (id)init;
- (void)cancel:(id)arg1;
- (void)enterPassword:(id)arg1;
- (void)enterUsername:(id)arg1;
- (void)login:(id)arg1;
- (id)username;
- (void)setUsername:(id)arg1;
- (id)password;
- (void)setMessageText:(id)arg1;
- (int)runModal;
- (BOOL)savePassword;
- (void)setSavePassword:(BOOL)arg1;

@end

