//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocumentController.h"

@interface JGDocumentController : NSDocumentController
{
    id delegate;
}

- (id)delegate;
- (void)setDelegate:(id)arg1;
- (int)runModalOpenPanel:(id)arg1 forTypes:(id)arg2;

@end

