//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@class NSDictionary;

@interface JGExtendedTextView : NSTextView
{
    BOOL autoIndents;
    NSDictionary *externalEditingSession;
}

+ (id)fullyConfiguredTextView;
- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (BOOL)autoIndents;
- (void)setAutoIndents:(BOOL)arg1;
- (void)toggleAutoIndent:(id)arg1;
- (void)toggleSoftWrap:(id)arg1;
- (void)jaguarReplaceTextInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;
- (void)insertNewline:(id)arg1;
- (void)insertFromFile:(id)arg1;
- (void)insertFromFileDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)insertFromURL:(id)arg1;
- (void)insertFromURLDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (BOOL)validateMenuItem:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (BOOL)isEditingInExternalEditor;
- (void)savePropertiesForExternalEdit;
- (void)restorePropertiesForExternalEdit;
- (void)editInExternalEditor:(id)arg1;
- (void)cancelOperation:(id)arg1;
- (void)cancelAlertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)odbEditor:(id)arg1 didModifyFileForString:(id)arg2 context:(void *)arg3;
- (void)odbEditor:(id)arg1 didCloseFileForString:(id)arg2 context:(void *)arg3;
- (void)didChangeText;
- (void)goToLine:(id)arg1;
- (void)goToLineDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (id)lineNumberingRulerView:(id)arg1 lineRectsForRect:(struct _NSRect)arg2;
- (BOOL)lineNumbersVisible;
- (void)setLineNumbersVisible:(BOOL)arg1;
- (void)toggleLineNumbers:(id)arg1;

@end

