//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSInvocation, NSString, NSTextField;

@interface JGInputRequest : NSWindowController
{
    NSButton *cancelButton;
    NSButton *okayButton;
    NSButton *helpButton;
    NSTextField *inputTextField;
    NSTextField *messageTextField;
    id delegate;
    NSInvocation *sheetDidEndInvocation;
    BOOL inModalSession;
    BOOL allowsEmptyInputString;
    NSString *helpAnchor;
}

+ (id)request;
- (id)init;
- (void)dealloc;
- (int)runModal;
- (void)beginSheetModalForWindow:(id)arg1 modalDelegate:(id)arg2 didEndSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)validateOkayButton;
- (void)windowDidLoad;
- (void)controlTextDidChange:(id)arg1;
- (void)cancel:(id)arg1;
- (void)okay:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)messageText;
- (void)setMessageText:(id)arg1;
- (id)inputString;
- (void)setInputString:(id)arg1;
- (BOOL)allowsEmptyInputString;
- (void)setAllowsEmptyInputString:(BOOL)arg1;
- (BOOL)showsHelp;
- (void)setShowsHelp:(BOOL)arg1;
- (id)helpAnchor;
- (void)setHelpAnchor:(id)arg1;
- (void)showHelp:(id)arg1;

@end

