//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutManager.h"

@interface JGLayoutManager : NSLayoutManager
{
}

- (unsigned int)lineNumberForPoint:(struct _NSPoint)arg1 inTextContainer:(id)arg2;
- (struct _NSRange)lineNumberRangeForBoundingRect:(struct _NSRect)arg1 inTextContainer:(id)arg2;

@end

