//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSResponder.h"

@class NSView;

@interface JGPreferencePane : NSResponder
{
    NSView *contentView;
    BOOL contentViewLoaded;
}

- (id)init;
- (void)dealloc;
- (id)nibName;
- (void)loadContentView;
- (void)contentViewDidLoad;
- (id)contentView;
- (void)setContentView:(id)arg1;
- (id)title;
- (id)image;
- (void)willBecomeCurrent;
- (void)didBecomeCurrent;
- (void)willResignCurrent;
- (void)didResignCurrent;

@end

