//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSArray;

@interface JGPreferenceWindowController : NSWindowController
{
    NSArray *prefPanes;
    id delegate;
}

+ (id)sharedController;
- (id)init;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)windowDidLoad;
- (id)toolbarItemIdentifierForPaneIndex:(unsigned int)arg1;
- (unsigned int)paneIndexForToolbarItemIdentifier:(id)arg1;
- (void)switchPane:(id)arg1;
- (unsigned int)selectedPaneIndex;
- (void)setSelectedPaneIndex:(unsigned int)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarSelectableItemIdentifiers:(id)arg1;
- (BOOL)validateToolbarItem:(id)arg1;

@end

