//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JaguarAppKit/JGSoftwareUpdateChecker.h>

@interface JGSoftwareUpdateChecker (Private)
- (id)requestForChecking;
- (id)infoFromData:(id)arg1;
- (void)runBackgroundThread:(id)arg1;
- (void)backgroundThreadDidComplete:(id)arg1;
@end

