//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, NSURL;

@interface JGSoftwareUpdateChecker : NSObject
{
    NSURL *infoURL;
    NSString *bundleIdentifier;
    NSString *branchIdentifier;
    id client;
    id asyncResult;
    NSError *asyncError;
}

+ (id)checkerWithBundle:(id)arg1 client:(id)arg2;
- (id)initWithURL:(id)arg1 bundleIdentifier:(id)arg2 branchIdentifier:(id)arg3 client:(id)arg4;
- (void)dealloc;
- (id)runSynchronouslyReturningError:(id *)arg1;
- (void)runInBackground;

@end

