//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextStorage.h"

@class NSMutableAttributedString;

@interface JGTextStorage : NSTextStorage
{
    struct vector<_NSRange, std::allocator<_NSRange>> *lineRangesCache;
    BOOL lineRangesCacheIsDirty;
    NSMutableAttributedString *attributedString;
}

- (id)init;
- (void)dealloc;
- (id)string;
- (id)attributesAtIndex:(unsigned int)arg1 effectiveRange:(struct _NSRange *)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)setAttributes:(id)arg1 range:(struct _NSRange)arg2;
- (void)edited:(unsigned int)arg1 range:(struct _NSRange)arg2 changeInLength:(int)arg3;
- (unsigned int)countOfLines;
- (struct _NSRange)lineNumberRangeForRange:(struct _NSRange)arg1;
- (struct _NSRange)lineNumberRangeForRange:(struct _NSRange)arg1 firstLineHint:(unsigned int)arg2;
- (struct _NSRange)rangeForLineNumberRange:(struct _NSRange)arg1;
- (id)lineRanges;
- (void)jg_calculateLineRangesUpToLocation:(unsigned int)arg1;

@end

