//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (JGAppKitExtensions)
+ (id)bezierPathWithRoundedRect:(struct _NSRect)arg1 radius:(float)arg2 roundedCorners:(int)arg3;
+ (id)bezierPathWithRoundedRect:(struct _NSRect)arg1 radius:(float)arg2;
- (void)strokeInside;
- (void)strokeInsideWithinRect:(struct _NSRect)arg1;
@end

