//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSplitView.h"

@interface NSSplitView (JGAppKitExtensions)
- (id)layoutPropertyList;
- (void)restoreLayoutFromPropertyList:(id)arg1;
- (float)subviewRatio;
- (void)adjustSubviewsWithRatio:(float)arg1;
@end

