//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface ODBEditor : NSObject
{
    unsigned int _signature;
    NSString *_editorBundleIdentifier;
    NSMutableDictionary *_filesBeingEdited;
}

+ (id)sharedODBEditor;
- (id)init;
- (void)dealloc;
- (void)setEditorBundleIdentifier:(id)arg1;
- (id)editorBundleIdentifier;
- (void)abortEditingFile:(id)arg1;
- (void)abortAllEditingSessionsForClient:(id)arg1;
- (BOOL)editFile:(id)arg1 options:(id)arg2 forClient:(id)arg3 context:(void *)arg4;
- (BOOL)editString:(id)arg1 options:(id)arg2 forClient:(id)arg3 context:(void *)arg4;

@end

