//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct FSRef {
    unsigned char _field1[80];
};

struct FSSpec {
    short _field1;
    long _field2;
    unsigned char _field3[64];
};

struct JGFrameSetRect {
    struct _NSRect _field1;
    void *_field2;
    char _field3;
};

struct _NSPoint {
    float x;
    float y;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};

