//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSError, NSFileHandle, NSMutableData, NSTask, NSTimer;

@interface JGBufferedTask : NSObject
{
    unsigned long long maximumOutputSize;
    unsigned long long accumulatedOutputSize;
    NSTimer *executionTimer;
    double maximumExecutionTime;
    NSDate *launchDate;
    NSMutableData *inputBuffer;
    NSMutableData *outputBuffer;
    NSMutableData *errorBuffer;
    NSTask *lowLevelTask;
    NSFileHandle *inputFileHandle;
    NSFileHandle *outputFileHandle;
    NSFileHandle *errorFileHandle;
    NSError *terminationError;
}

- (id)init;
- (void)dealloc;
- (id)lowLevelTask;
- (double)maximumExecutionTime;
- (void)setMaximumExecutionTime:(double)arg1;
- (unsigned long long)maximumOutputSize;
- (void)setMaximumOutputSize:(unsigned long long)arg1;
- (double)elapsedExecutionTime;
- (unsigned long long)accumulatedOutputSize;
- (id)inputBuffer;
- (id)outputBuffer;
- (id)errorBuffer;
- (void)launch;
- (void)flushInputData;
- (void)bufferedTask_doFlushInputDataInBackground:(id)arg1;
- (void)flushInputDataInBackground;
- (void)abort;
- (void)waitUntilExit;
- (void)waitUntilReadingComplete;
- (void)lowLevelTaskDidLaunch;
- (void)lowLevelTaskDidTerminate;
- (void)lowLevelTaskOutputCompleted;
- (void)maximumExecutionTimeExceeded;
- (void)maximumOutputSizeExceeded;
- (void)postTerminateNotification;
- (void)readToEndOfFileCompleted:(id)arg1;
- (void)readInBackgroundCompleted:(id)arg1;
- (void)executionTimerDidFire:(id)arg1;

@end

