//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface JGDownloadQueue : NSObject
{
    NSMutableDictionary *connectionDict;
    id client;
}

- (id)initWithClient:(id)arg1;
- (void)dealloc;
- (void)registerDictionary:(id)arg1 forConnection:(id)arg2;
- (void)unregisterDictionaryForConnection:(id)arg1;
- (id)dictionaryForConnection:(id)arg1;
- (void)queueRequest:(id)arg1 userInfo:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;

@end

