//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JGFrameSet : NSObject
{
    struct JGFrameSetRect *frames;
    unsigned int frameCount;
}

- (id)init;
- (void)dealloc;
- (struct _NSRect)frameAtIndex:(unsigned int)arg1;
- (void *)userInfoAtIndex:(unsigned int)arg1;
- (unsigned int)count;
- (unsigned int)indexOfFrameAtPoint:(struct _NSPoint)arg1;
- (struct _NSRect)enclosingFrame;

@end

