//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface JGHashCache : NSObject
{
    int algorithm;
    NSMutableDictionary *hashes;
}

- (id)initWithAlgorithm:(int)arg1;
- (void)dealloc;
- (id)hashForString:(id)arg1;
- (void)addHashForString:(id)arg1;
- (void)removeHashForString:(id)arg1;
- (id)stringWithHash:(id)arg1;

@end

