//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JGXMLRPCInvocation : NSObject
{
    struct OpaqueWSMethodInvocationRef *invocation;
    id result;
    id client;
    SEL clientSelector;
}

+ (id)resultOfInvokingURL:(id)arg1 methodName:(id)arg2 parameters:(id)arg3;
+ (id)invocationWithURL:(id)arg1 methodName:(id)arg2 parameters:(id)arg3;
- (id)initWithURL:(id)arg1 methodName:(id)arg2 parameters:(id)arg3;
- (void)dealloc;
- (BOOL)isFault;
- (id)error;
- (id)faultString;
- (int)faultCode;
- (id)result;
- (id)invoke;
- (void)invokeAndNotify:(id)arg1 withSelector:(SEL)arg2;

@end

