//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JaguarFoundation/NDAlias.h>

@interface NDAlias (AliasFile)
+ (id)aliasWithContentsOfFile:(id)arg1;
+ (id)aliasWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (BOOL)writeToFile:(id)arg1;
- (BOOL)writeToURL:(id)arg1;
@end

