//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NDResourceFork : NSObject
{
    short fileReference;
}

+ (id)resourceForkForReadingAtURL:(id)arg1;
+ (id)resourceForkForWritingAtURL:(id)arg1;
+ (id)resourceForkForReadingAtPath:(id)arg1;
+ (id)resourceForkForWritingAtPath:(id)arg1;
- (id)initForReadingAtURL:(id)arg1;
- (id)initForWritingAtURL:(id)arg1;
- (id)initForPermission:(BOOL)arg1 AtURL:(id)arg2;
- (id)initForPermission:(BOOL)arg1 AtPath:(id)arg2;
- (id)initForReadingAtPath:(id)arg1;
- (id)initForWritingAtPath:(id)arg1;
- (void)dealloc;
- (BOOL)addData:(id)arg1 type:(unsigned long)arg2 Id:(short)arg3 name:(id)arg4;
- (BOOL)addData:(id)arg1 type:(unsigned long)arg2 name:(id)arg3;
- (id)dataForType:(unsigned long)arg1 Id:(short)arg2;
- (id)dataForType:(unsigned long)arg1 named:(id)arg2;
- (id)everyResourceType;
- (BOOL)removeType:(unsigned long)arg1 Id:(short)arg2;
- (id)nameOfResourceType:(unsigned long)arg1 Id:(short)arg2;
- (BOOL)getId:(short *)arg1 ofResourceType:(unsigned long)arg2 named:(id)arg3;
- (BOOL)getAttributeFlags:(short *)arg1 forResourceType:(unsigned long)arg2 Id:(short)arg3;
- (BOOL)setAttributeFlags:(short)arg1 forResourceType:(unsigned long)arg2 Id:(short)arg3;
- (id)dataForEntireResourceFork;
- (BOOL)writeEntireResourceFork:(id)arg1;

@end

