//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (JGFoundationExtensions)
- (unsigned int)indexOfObjectWithValue:(id)arg1 forKey:(id)arg2;
- (unsigned int)indexOfObjectWithIdenticalValue:(id)arg1 forKey:(id)arg2;
- (id)objectWithValue:(id)arg1 forKey:(id)arg2;
- (id)objectWithIdenticalValue:(id)arg1 forKey:(id)arg2;
@end

