//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (JGHexString)
+ (id)dataWithHexString:(id)arg1;
+ (id)dataWithHexData:(id)arg1;
- (id)initWithHexString:(id)arg1;
- (id)initWithHexData:(id)arg1;
- (id)hexData;
- (id)hexString;
@end

