//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (JGFoundationExtensions)
+ (id)stringWithContentsOfURL:(id)arg1 error:(id *)arg2;
+ (id)stringByGuessingEncodingOfData:(id)arg1;
+ (id)IANANameOfStringEncoding:(unsigned int)arg1;
- (id)lineRanges;
- (id)stringWithLineEndings:(int)arg1;
- (id)commandLineComponents;
- (id)stringByReplacingPlaceholdersStartingWith:(id)arg1 withStringsFromDictionary:(id)arg2 options:(int)arg3;
- (id)stringByEncodingForURLQueryComponent;
@end

