//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NDCarbonUtilitiesPaths)
+ (id)stringWithFSRef:(const struct FSRef *)arg1;
+ (id)stringWithPascalString:(const char *)arg1;
- (BOOL)getFSRef:(struct FSRef *)arg1;
- (BOOL)getFSSpec:(struct FSSpec *)arg1;
- (id)fileSystemPathHFSStyle;
- (id)pathFromFileSystemPathHFSStyle;
- (id)resolveAliasFile;
- (BOOL)getPascalString:(char *)arg1 length:(short)arg2;
- (const char *)pascalString;
- (id)trimWhitespace;
- (BOOL)finderInfoFlags:(unsigned short *)arg1 type:(unsigned int *)arg2 creator:(unsigned int *)arg3;
- (struct _NSPoint)finderLocation;
- (BOOL)setFinderInfoFlags:(unsigned short)arg1 mask:(unsigned short)arg2 type:(unsigned long)arg3 creator:(unsigned long)arg4;
- (BOOL)setFinderLocation:(struct _NSPoint)arg1;
@end

